#cloud-config

package_update: true
package_upgrade: true
packages:
  - python3
  - python3-pip
  - sqlite3

runcmd:
  - cd /home/ubuntu/THINK-HIVE
  - python3 -m venv venv
  - . venv/bin/activate
  - pip install -r requirements.txt
  - python3 backend/app.py
